routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductController@index');
Route::get('product/data', 'ProductController@data')->name('product.data');
Route::resource('product', 'ProductController');

Route::get('subcategory/{id}', 'SubCategoryController@search')->name('subcategory.search');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'category';
    protected $fillable = [
        'name'
    ];

    public $timestamps = false;

    // fk
    public function product(){
        $this->hasMany('App\Models\TableBE', 'category');
    }

    public function subCategory(){
        $this->hasMany('App\Models\SubCategory', 'parent');
    }
}

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $table = 'subcategory';
    protected $fillable = [
        'name', 'parent'
    ];

    public $timestamps = false;

    // fk
    public function product(){
        $this->hasMany('App\Models\TableBE', 'subcategory');
    }

    public function category(){
        $this->belongsTo('App\Models\Category', 'parent');
    }
}

app/Models/TabelBE.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TabelBE extends Model
{
    protected $table = 'tabelbe';
    protected $fillable = [
        'title_product', 'brands', 'gender', 'category', 'subcategory', 'keterangan'
    ];

    public $timestamps = false;

    // fk
    public function Category(){
        return $this->belongsTo('App\Models\Category', 'category');
    }

    public function subCategory(){
        return $this->belongsTo('App\Models\SubCategory', 'subcategory');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Models\Category;
use App\Models\SubCategory;
use App\Models\tabelBE as Product;

use DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['category'] = Category::all();
        if($request->ajax()){
            $arr = [];
            $no = 1;
            $product = Product::all();
            
            return datatables()->of($product)
                                ->addColumn('action', function($data){
                                    $button = '<button class="btn btn-primary btn-sm mr-2 view" data-id="'.$data->id.'">View</button>';
                                    $button .= '<button class="btn btn-danger btn-sm delete" data-id="'.$data->id.'">Delete</button>';

                                    return $button;
                                })
                                ->addColumn('categoryName', function($data){
                                    return $data->Category->name;
                                })
                                ->addColumn('subCategoryName', function($data){
                                    return $data->subCategory->name;
                                })
                                ->rawColumns(['action', 'categoryName', 'subCategoryName'])
                                ->addIndexColumn()
                                ->make(true);
        }

        return view('layouts.product.index', $data);
    }

    public function data(){
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'title_product' => 'required|min:4',
            'brands' => 'required|min:4',
            'gender' => 'required',
            'category' => 'required',
            'subcategory' => 'required'
        ], [
            'required' => 'Kolom ini tidak boleh kosong!',
            'min' => 'Minimal panjang karakter :min'
        ]);

        if($validate->fails()){
            return response()->json([
                'success' => false,
                'message' => $validate->getMessageBag()->toArray()
            ]);
        }else{
            Product::create([
                'title_product' => $request->title_product,
                'brands' => $request->brands,
                'gender' => $request->gender,
                'category' => $request->category,
                'subcategory' => $request->subcategory,
                'keterangan' => $request->keterangan
            ]);
            return response()->json(['success' => true]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::find($id);

        return response()->json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Product::find($id);
        $data->delete();
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\SubCategory;

class SubCategoryController extends Controller
{
    public function search($id){
        $data = SubCategory::where('parent', $id)->get();

        return response()->json($data);
    }
}

resources/views/app/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    @include('page.head')
  </head>
  <body>
    <!-- navbar -->
    @include('page.navbar')
    <!-- navbar -->

    <!-- content -->
    <div class="container mt-3">
      @yield('content')
    </div>
    <!-- content -->

    <!-- modal -->
    @yield('modal')
    <!-- modal -->

    <!-- Optional JavaScript -->
    @include('page.javascript')
    @stack('javascript')
  </body>
</html>

resources/views/layouts/product/index.blade.php
@extends('app.master')

@section('content')
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          New Product
        </div>
        <div class="card-body">
          <form>
            <div class="form-group">
              <label for="title_product">Title Product</label>
              <input type="text" name="title_product" class="form-control" id="title_product">
              
              <!-- error -->
              <small class="text-danger error_title_product"></small>
            </div>

            <div class="form-group">
              <label for="brands">Brands</label>
              <input type="text" name="brands" class="form-control" id="brands">
              
              <!-- error -->
              <small class="text-danger error_brands"></small>
            </div>

            <div class="form-group">
              <label for="gender">Gender</label>
              <select name="gender" id="gender" class="form-control">
                <option value="">-- Select Gender --</option>
                <option value="man">Man</option>
                <option value="woman">Woman</option>
              </select>
              
              <!-- error -->
              <small class="text-danger error_gender"></small>
            </div>

            <div class="form-group">
              <label for="category">Category</label>
              <select name="category" id="category" class="form-control">
                <option value="">-- Select Category --</option>
                @foreach($category as $ctr)
                  <option value="{{ $ctr->id }}">{{ $ctr->name }}</option>
                @endforeach
              </select>
              
              <!-- error -->
              <small class="text-danger error_category"></small>
            </div>

            <div class="form-group subcategory">

            </div>

            <div class="form-group">
              <label for="keterangan">Keterangan</label>
              <textarea name="keterangan" id="keterangan" class="form-control" rows="5"></textarea>
            </div>

            <button class="btn btn-primary btn-block text-center btn-submit">Simpan</button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card">
        <div class="card-header text-center">
          List Product
        </div>
        <div class="card-body">
          <table class="table table-bordered product" style="font-size:.7em">
            <thead>
              <tr>
                <th>No</th>
                <th>Title Product</th>
                <th>Brand</th>
                <th>Gender</th>
                <th>Category</th>
                <th>Sub Category</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  
@endsection

@section('modal')

@endsection

@push('javascript')
  <script>
    $(document).ready(function(){
      $('.product').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('product.index') }}",
        columns:[
          { data: 'DT_RowIndex', name: 'DT_RowIndex' },
          { data: 'title_product', name: 'title_product' },
          { data: 'brands', name: 'brands' },
          { data: 'gender', name: 'gender' },
          { data: 'categoryName', name: 'categoryName' },
          { data: 'subCategoryName', name: 'subCategoryName' },
          { data: 'action', name: 'action', orderable:false }
        ]
      });

      // view subcategory
      $('#category').on('change', function(){
        let categoryId = $(this).val();
        
        $.ajax({
          url: "{{ url('subcategory') }}"+'/'+categoryId,
          type: 'GET',
          success: function(data){
            let subCategory = $('.subcategory');
            subCategory.empty();
            subCategory.append(`
              <label for="subcategory">Sub Category</label>
              <select name="subcategory" id="subcategory" class="form-control">
              </select>
            `);
            $.each(data, function(){
              $('#subcategory').append(`<option value="`+this.id+`">`+this.name+`</option>`);
            });

            subCategory.append(`<small class="text-danger error_subcategory"></small>`);
          },
          error: function(){
						alert('Error!')
					}
        });
      });

      // simpan data
      $('.btn-submit').on('click', function(e){
        e.preventDefault();
        let title_product = $('#title_product').val();
        let brands = $('#brands').val();
        let gender = $('#gender').val();
        let category = $('#category').val();
        let subcategory = $('#subcategory').val();
        let keterangan = $('#keterangan').val();

        $.ajax({
          url: "{{ route('product.store') }}",
          type: 'POST',
          data: {
            '_token' : '{{ csrf_token() }}',
            'title_product' : title_product,
            'brands' : brands,
            'gender' : gender,
            'category' : category,
            'subcategory' : subcategory,
            'keterangan' : keterangan
          },
          success: function(data){
            if(data.success == false){
              sendValidator(data.message);
            }else{
              swal({
                title: "Success!",
                text: "Simpan data berhasil.",
                icon: "success",
                button: "OK",
              });
              let table = $('.product').DataTable();
              table.ajax.reload();
              
              // empty
              let subCategory = $('.subcategory');
              subCategory.empty();
              $('#title_product').val('');
              $('#brands').val('');
              $('#gender').val('');
              $('#category').val('');
              $('#keterangan').val('');
            }
          },
          error: function(){
						alert('Error!')
					}
        });
      });

      function sendValidator(message){
        let title_product = $('.error_title_product');
        let brands = $('.error_brands');
        let gender = $('.error_gender');
        let category = $('.error_category');
        let subcategory = $('.error_subcategory');

        title_product.empty();
        brands.empty();
        gender.empty();
        category.empty();
        subcategory.empty();

        if(message.title_product){
          title_product.append(message.title_product[0]);
        }
        if(message.brands){
          brands.append(message.brands[0]);
        }
        if(message.gender){
          gender.append(message.gender[0]);
        }
        if(message.category){
          category.append(message.category[0]);
        }
        if(message.subcategory){
          subcategory.append(message.subcategory[0]);
        }
      }
    });

    // view data
    $(document).on('click', '.view', function(){
      let id = $(this).data('id');

      $.ajax({
        url: "{{ url('product') }}"+'/'+id,
        type: 'GET',
        success: function(data){
          swal(data.title_product, data.keterangan);
        },
          error: function(){
						alert('Error!')
					}
      });
    });

    // delete data
    $(document).on('click', '.delete', function(){
      let id = $(this).data('id');

      swal({
        title: "Delete data product?",
        text: "Data akan terhapus secara permanen!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
          $.ajax({
            url: "{{ url('product') }}"+'/'+id,
            type: 'DELETE',
            data: {
              '_token' : '{{ csrf_token() }}'
            },
            success: function(){
              let table = $('.product').DataTable();
              table.ajax.reload();
            },
            error: function(){
              alert('Error!')
            }
          });
        }
      });
    });
  </script>
@endpush

resources/views/page/head.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">

<title>{{ env('APP_NAME') }}</title>

resources/views/page/javascript.blade.php
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<!-- datatable -->
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>

<!-- sweetalert -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

resources/views/page/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">{{ env('APP_NAME') }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{{ route('product.index') }}">Product</a>
      </div>
    </div>
  </div>
</nav>